# Generated by Django 3.2 on 2021-04-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=128, verbose_name='user_hash')),
                ('avg_mood_score', models.FloatField(default=0, verbose_name='avg_mood_score')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.CharField(max_length=1028, verbose_name='msg_text')),
                ('timestamp', models.IntegerField(verbose_name='timestamp')),
                ('is_bot', models.BooleanField(verbose_name='is_sender')),
                ('compound_score', models.FloatField(default=-6.0, verbose_name='compound_score')),
                ('neg_score', models.FloatField(default=-6.0, verbose_name='neg_score')),
                ('neu_score', models.FloatField(default=-6.0, verbose_name='neu_score')),
                ('pos_score', models.FloatField(default=-6.0, verbose_name='pos_score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.user')),
            ],
        ),
    ]
